import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/shared/navbar";
import { NextThemeProvider } from "@/providers/theme";
import ReduxProvider from "@/providers/redux";
import { Toaster } from "@/components/ui/sonner";

const garamount = EB_Garamond({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garamount.className} relative w-full `}>
        <ReduxProvider>
          <NextThemeProvider>
            {children}

            <Toaster />
          </NextThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
